setwd("C:/Users/Jack/Documents/R/data explo/week 1")
consumption <- read.table("household_power_consumption.txt", header = TRUE, sep = ";")
consumption$Date <- as.Date(consumption$Date, format = "%d/%m/%Y")
library(dplyr)
new_consumption <- filter(consumption, Date == "2007-02-01" | Date == "2007-02-02")
library(lubridate)
global <- as.numeric(as.character(new_consumption$Global_active_power))
datetime <- paste(new_consumption$Date, new_consumption$Time)
datetime <- as.POSIXct(datetime)
png('plot2.png')
plot(datetime, global, type = "l", ylab = "Global Active Power (kilowatts)", xlab = "")
dev.off()