setwd("C:/Users/Jack/Documents/R/data explo/week 1")
consumption <- read.table("household_power_consumption.txt", header = TRUE, sep = ";")
consumption$Date <- as.Date(consumption$Date, format = "%d/%m/%Y")
library(dplyr)
new_consumption <- filter(consumption, Date == "2007-02-01" | Date == "2007-02-02")
library(lubridate)
datetime <- paste(new_consumption$Date, new_consumption$Time)
datetime <- as.POSIXct(datetime)
png('plot3.png')
plot(datetime, as.numeric(as.character(new_consumption$Sub_metering_1)), type = "l", 
     xlab = "", ylab = "Energy sub metering")
lines(datetime, as.numeric(as.character(new_consumption$Sub_metering_2)), col = "red")
lines(datetime, as.numeric(as.character(new_consumption$Sub_metering_3)), col = "blue")
legend("topright",legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), 
       lwd = 2, col = c("black","blue","red"))
dev.off()